name: Waka Readme

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme
    runs-on: ubuntu-20.04
    steps:
      - uses: gccio/pretty-profile-readme@v1.0.0
        env:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          timezoneLinux: "Asia/Shanghai"
          
